### ISSUE TITLE
Mini-Games

### ISSUE THREAD

**Issue by michelfinley** [sloukit/pydew-valley-uzh#111]
Top-level issue to track the implementation of mini-games.

## Progress
- [X] #64 
  - create a new "Animal" class that implements all the unique properties of animals
  - add the animal sprites from the Sprout Lands asset pack

- [X] #102 
  - a new mini-game map with two separate areas in front of a barn, with a couple of obstacles

- [x] #112
  - prepare the addition of minigames
    - restrict the player's movement and interaction options and switch the NPC behaviour to a mini-game specific mode
    - add scoreboards that allow the player to track certain mini-game specific data, and a timer showing how much time is left on the mini-game that triggers some function when the mini-game is over
  - add a first minigame by fusing the new features together

## Labels
https://github.com/sloukit/pydew-valley-uzh/labels/game-levels https://github.com/sloukit/pydew-valley-uzh/labels/priority%3A%20high https://github.com/sloukit/pydew-valley-uzh/labels/type%3A%20feature

**Comment by fortwoone** [comment]
We now have one minigame, is it necessary to leave this open?
