### ISSUE TITLE
Bug: Plants are not persistent

### ISSUE THREAD

**Issue by 13-Sonja** [sloukit/pydew-valley-uzh#122]
#### Bug Description
Any plants that have been planted on the farm vanish when leaving the map and returning.

#### Expected Behavior
Plants should be persistent, otherwise the player can't ever leave the farm or never plant anything.

#### Steps to Reproduce
1. Plant stuff
2. Leave the farm map
3. Return to farm map

#### Additional Context
Would that be no issue once there are NPCs on the farm?

### Version

0.1.0

### Which aspect(s) of the project is this bug affecting?

game-design, game-gameplay

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by fortwoone** [comment]
I believe this is relevant to the save file, but I'm not sure how to tackle this, as it would potentially bloat the save file to save plants inside... will have to look into this soonish
