### ISSUE TITLE
NPC behavior

### ISSUE THREAD

**Issue by michelfinley** [sloukit/pydew-valley-uzh#133]
NPCs behavior (i.e., their looks); insert sprites according to the condition in which the study participant plays the game (1. group members wear the goggles, 2. group members don't wear the goggles). [see here](https://docs.google.com/spreadsheets/d/1NAssjrPN4mv3kBC3e5YmJcYkJZLU7450cFR9EhCbfgE/edit?gid=374591304#gid=374591304&range=13:14)

- [x] #132

**Comment by sloukit** [comment]
NPC farming behavior should be expanded:

- Farm specific tiles in an ordered pattern (i.e., each NPC farms a specific row of tiles and nowhere else).
- Add NPCs to the village map that walk around randomly.

**Comment by sloukit** [comment]
Thank you! 

- Add NPCs to the village map that walk around randomly.
You said that this has been implemented in PR#192, but there are yet no NPCs walking around the town map. Could you check this again, please?
