### ISSUE TITLE
Bug: Crash when showing TextBox dialog

### ISSUE THREAD

**Issue by larsbutler** [sloukit/pydew-valley-uzh#135]
#### Bug Description
The game crashes when opening a TextBox dialog:

```
Traceback (most recent call last):
  File "/path/to/pydew-valley-uzh/main.py", line 228, in <module>
    game.run()
  File "/path/to/pydew-valley-uzh/main.py", line 221, in run
    self.all_sprites.draw(self.level.camera)
  File "/path/to/pydew-valley-uzh/src/groups.py", line 60, in draw
    sprite.draw(self.display_surface, camera.apply(sprite), camera)
TypeError: TextBox.draw() takes 3 positional arguments but 4 were given
```

I discovered this by just starting the game, running around, and mashing keys.

#### Expected Behavior
Game shouldn't crash, the TextBox should be displayed and rendered correctly.

#### Steps to Reproduce
1. Start the game
2. Click Play
3. Press "t"

### Version

0.1.0

### Which aspect(s) of the project is this bug affecting?

game-ui, game-gameplay

### Relevant log output

```shell
Traceback (most recent call last):
  File "/path/to/pydew-valley-uzh/main.py", line 228, in <module>
    game.run()
  File "/path/to/pydew-valley-uzh/main.py", line 221, in run
    self.all_sprites.draw(self.level.camera)
  File "/path/to/pydew-valley-uzh/src/groups.py", line 60, in draw
    sprite.draw(self.display_surface, camera.apply(sprite), camera)
TypeError: TextBox.draw() takes 3 positional arguments but 4 were given
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by fortwoone** [comment]
Which branch does this affect?

**Comment by fortwoone** [comment]
So basically you ended up pressing "T", and since the text box feature is basically unused right now it crashed due to not being updated since a while

**Comment by richkdev** [comment]
The draw function in the `AllSprites` sprite group assumes that the sprites it draws have the same parameters, including the `TextBox` sprite, which supposedly has 4 parameters but only has 3. Adding a `camera` parameter to the `draw` function of `TextBox` sprite seemed to bring back the text box feature's functionality. I'll submit a pull request that fixes this issue.
