### ISSUE TITLE
Bug: Player camera zooming in cinamatic zoom areas near lake

### ISSUE THREAD

**Issue by DangerousVanilla** [sloukit/pydew-valley-uzh#142]
#### Bug Description
When entering the lake area near the lower right you're presented with a small cinamatic camera pan around the area before control and focus is returned to the player. There a area a couple of areas where the camera zoom in during the cinamatic sequence, however, if the player proceeds to these areas during normal play after the sequence ends the player's main camera zooms in while in these areas.

#### Expected Behavior
You would expect that the player controllable camera remains at the normal zoom level when walking through these areas and that these cinamatic zooms (if they're even intentional) don't effect the area itself, just the camera panning sequence initially.

#### Steps to Reproduce
1. Start a new game and proceed to the lake area (lower right).
2. Watch the cinamatic camera zoom sequence and note where the camera zoom in during the panning.
3. Once focus returns to your character, walk to the area where the camera had zoomed in during the initial camera sequence.
4. You'll notice the camera zooms in simply by being in that area.

#### Additional Context
Compare the camera zoom levels on the images below - the top is the incorrect zoomed in version when walking around the pink flower while the bottom is the correct zoom level when stepping just to the left. There is an area that does this here next to the small pink flower and tree (stump here cause it was cut down). This area is near the left entrance. The second area that does this is near the other blue flower to the north of this area (not the one in the picture here, further up by the water).

### Version

0.1.0

### Which aspect(s) of the project is this bug affecting?

game-gameplay

### Screenshots

![Bug_CameraZoomsInCertainAreas](https://github.com/user-attachments/assets/6d18ff41-2778-49e2-bbd9-a6337b3fa99a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by DangerousVanilla** [comment]
This has been resolved by PR188 - thank you very much @ZedKay52!

**Comment by ZedKay52** [comment]
You are welcome @DangerousVanilla :)
