### ISSUE TITLE
Bug: Pause Menu Malfunction

### ISSUE THREAD

**Issue by bucket91** [sloukit/pydew-valley-uzh#165]
#### Bug Description
...Pause menu doesn't seem to stop the timer and rain particle spawner

#### Additional Context
check main.py file around line 220 where the level is being updated per frame

the screenshot provided has a possible fix for the issue added as comments 

### Version

0.1.0

### Which aspect(s) of the project is this bug affecting?

area: code quality

### Screenshots

![Screenshot 2024-09-27 160218](https://github.com/user-attachments/assets/35952b34-b05a-4a67-9a5d-24f3aec5b169)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by DangerousVanilla** [comment]
Fixed in pull request #166 (thanks bucket91)
