### ISSUE TITLE
bug: options menu erasure 

### ISSUE THREAD

**Issue by pmp-p** [sloukit/pydew-valley-uzh#168]
### Describe the bug

When quitting "options"  the options menu is not erased under and main menu superimpose

### Version

0.1.0

### Which aspect(s) of the project is this bug affecting?

game-ui

### Screenshots

![shot-2024-09-29_1727578495](https://github.com/user-attachments/assets/6d3325e4-1f27-4f33-94c9-d4836caeb767)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by pmp-p** [comment]
@SagarChandra07 please stop spamming exe or you will be reported.

**Comment by thelabcat** [comment]
> @SagarChandra07 please stop spamming exe or you will be reported.

Report them, it's malware.

**Comment by bucket91** [comment]
I found the issue should be fixed in my next PR

**Comment by bucket91** [comment]
fixed the faulty code but the sub menu is to the side anyway so the issue should be closed
