### ISSUE TITLE
Bug: Panting Seed is glitchy

### ISSUE THREAD

**Issue by bucket91** [sloukit/pydew-valley-uzh#187]
#### Bug Description
Right clicking to plant seed plants endlessly but using a keyboard button to plants seed only plants once.

#### Additional Context
See video attached

https://github.com/user-attachments/assets/a295d2ea-ee48-49ff-b960-95cdc4f503dd

### Version

0.1.0

### Which aspect(s) of the project is this bug affecting?

game-gameplay

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by michelfinley** [comment]
Nice catch! Found the source of the bug and will push a fix later today 🙂
