### ISSUE TITLE
Non-playable characters

### ISSUE THREAD

**Issue by michelfinley** [sloukit/pydew-valley-uzh#34]
#27 A basic implementation of non-playable characters in the form of two NPCs.
The NPCs will wander around and try to till, plant and water randomly selected tiles.

**Comment by fortwoone** [comment]
Whoops, accidentally closed this

**Comment by sloukit** [comment]
I think we should get rid of the sound that the NPC farming produces (tilling, planting, watering; using an axe)

**Comment by michelfinley** [comment]
You're right!
I'm currently working on expanding the behaviour of NPCs so that they can gather apples, chop wood, and that they choose the fields they till and the crops they plant a bit more logically. I think I can perfectly incorporate it there.

**Comment by sloukit** [comment]
Great! For the interactions: Is it possible for the NPC to approach the player during the interaction? I think right now the closest NPC reacts from where they are, but it would be nice if the closest NPC walked up to the player, reflected the player's interaction, and then walked away

**Comment by michelfinley** [comment]
Of course! Actually, I had already implemented this, but after testing it I realised that it could easily be abused. If you spam emotes, for example, you could then just lure the NPCs all over the map and distract from what they're wanting to do. I think a better way to achieve more interactivity between the Player and the NPCs might be to not have them walk towards the Player, but have them stay in place and turn towards the Player when they open the emote wheel.

**Comment by farg-eh** [comment]
can this be solved with a radius range for the interactions? i think walking to the player would be fun 🥺

**Comment by fortwoone** [comment]
> Of course! Actually, I had already implemented this, but after testing it I realised that it could easily be abused. If you spam emotes, for example, you could then just lure the NPCs all over the map and distract from what they're wanting to do. I think a better way to achieve more interactivity between the Player and the NPCs might be to not have them walk towards the Player, but have them stay in place and turn towards the Player when they open the emote wheel.

This could still be abused, but only to force NPCs to stand still. There should be some sort of cooldown, like 1 reaction to player emotes every 5 minutes or something like that

**Comment by farg-eh** [comment]
i think 5 minutes is an overkill we could just make it work when the player is close enough to the npc a distance such as 300-400 pixels should be decent this way far npcs that are already doing something wont be affected and close ones are available to mess with

a time out is also a good idea but for 5-8 seconds and when the timeout is over it could be indicated via the emote above the npc

 if it disappears then the npc can interact again

**Comment by fortwoone** [comment]
Actually, 8 seconds does seem balances
