### ISSUE TITLE
Add inventory screen

### ISSUE THREAD

**Issue by fortwoone** [sloukit/pydew-valley-uzh#38]
Participants should be able to see the seeds and harvest they have available (like the number of apples, the amount of corn etc.)

**Comment by fortwoone** [comment]
Okay, so adding an inventory screen is a task for this project. But what exactly should it offer alongside, well, displaying inventory resources? I thought it would be better to open an issue and ask the project directors about their opinions on this.

**Comment by fortwoone** [comment]
What do you mean by that?

**Comment by sloukit** [comment]
Something like this (see picture). Am I right that we decided  not to make an inventory, but to add the gallery with all items, including seeds, harvest to the menu. If that is the case, we might close this issue and work on the "menu" task in the list? 

![Image](https://github.com/user-attachments/assets/f8ad329b-5b74-4b90-a55b-c16240dd45f7)

**Comment by fortwoone** [comment]
Wait, so the resource count is for all the NPCs in the ingroup, not just for the player?

**Comment by fortwoone** [comment]
Okay, but what about the NPCs? @michelfinley implemented code for them to collect crops too, so they have their own inventory

**Comment by fortwoone** [comment]
If you mean to add a system such as "save some resources for the group", then I think this is not the role of the inventory menu, and that it should be moved to another thing entirely

**Comment by fortwoone** [comment]
Kind of like the Ender Chest from Minecraft, but shared between all members of the ingroup (which would mean that NPCs can also go put or take resources from there)

**Comment by sloukit** [comment]
Yes, we _could_ implement the resources from the NPCs, but it is not mandatory. If it's too time consuming, I'd skip it. But I cannot estimate how complex it is

**Comment by sloukit** [comment]
Okay, great!
