### ISSUE TITLE
Game crashes when cutting a tree

### ISSUE THREAD

**Issue by Manunz15** [sloukit/pydew-valley-uzh#39]
Right now there is the list of resources in too many places (in InventoryResource, in Entity etc...). I think we should remade all the inventory logic by creating a unique file where there is the full list and then all the other methods refer to it, in this way we can add resources much easier and avoid these problems.

**Comment by fortwoone** [comment]
That does not precise in which case the game crashes, nor the full traceback you get when said crash happens
