### ISSUE TITLE
Maps and scenes before volcanic eruption

### ISSUE THREAD

**Issue by Mega-JC** [sloukit/pydew-valley-uzh#47]
Top-level issue to track the creation of all maps and scenes before the volcanic eruption.

We need to make three different maps, using Tiled and the Sprout Lands premium asset pack (alongside decoration objects)

## Progress
- [ ] #66
  Map where all the farming of the ingroup and the outgroup is done (including fields to set seeds, a house, cows, chicken etc.)
- [x] #67
  Map for the (small) village, with some buildings, the marketplace, the house where the bath is taken. The house where the bath is taken should be outside the center, covered by some trees 
- [ ] #68
  Map for a forest, where fruits grow on trees/where where trees can be felled

**Comment by sloukit** [comment]
For the forest map: I think we should limit the use of tools on this map, except for the axe. For the village map: We should restrict all tool use
