### ISSUE TITLE
Main character wearing goggles and necklace

### ISSUE THREAD

**Issue by fortwoone** [sloukit/pydew-valley-uzh#77]
While we do have spritesheets ready in the cases where the player wears the hat and goggles together, we do not have this combo for the goggles and necklace. This has to be done so the player can choose which ones they want to wear.

**Comment by fortwoone** [comment]
Unless @sloukit says otherwise, this task is assigned to @yoadrienne48

**Comment by yoadrienne48** [comment]
These have been uploaded. I have a couple versions as I'm not sure what will translate best with the game.
